### ISSUE TITLE
Advertise the project

### ISSUE THREAD

**Issue by mmilata** [jvstein/bitcoin-prometheus-exporter#14]
Thanks for writing this nice exporter! I think it would be a good idea to add it to the [list of Prometheus exporters](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exporters.md) so it's easier to find. There's another bitcoin exporter which is in the list but I think this one is superior.

There's also [list of default port allocations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations).

**Comment by jvstein** [comment]
Feel free to open a pull request against the prometheus doc you referenced. I'm not likely to be proactive about it.

**Comment by mmilata** [comment]
Opened PR & added to the port list, let's close the issue.
