### ISSUE TITLE
Docker images for arm64 platform

### ISSUE THREAD

**Issue by maxhollmann** [jvstein/bitcoin-prometheus-exporter#20]
I'd like to use this for a bitcoin node running on a Raspberry Pi 4, but that requires an image for the arm64 platform. It should be possible to build multi-platform images using [Buildx](https://docs.docker.com/buildx/working-with-buildx/).

**Comment by maxhollmann** [comment]
In case anyone else needs this, I built an arm64-only image myself and pushed it [here](https://hub.docker.com/r/maxhollmann/bitcoin-prometheus-exporter/tags?page=1&ordering=last_updated) for now.

**Comment by jvstein** [comment]
Resolved in 6a621bce123c1834ee6a3f770785022e13717013 and included in the [0.6.0](https://github.com/jvstein/bitcoin-prometheus-exporter/releases/tag/v0.6.0) release.
