### ISSUE TITLE
rust port

### ISSUE THREAD

**Issue by eburghar** [jvstein/bitcoin-prometheus-exporter#23]
Thanks a lot for sharing this exporter !

I've just made a direct port of your work in rust: [bitcoin-exporter](https://github.com/eburghar/bitcoin-exporter)

Also perhaps in the near future prometheus scrapping will be even more efficient and exhaustive [bitcoind-observer](https://github.com/0xB10C/bitcoind-observer)

Regards

**Comment by jvstein** [comment]
Nice! I put a link to your port in the README. The "bitcoind-observer" project looked a little too experimental to link for now. Please open a PR to add anything else you find that's similar.
