### ISSUE TITLE
REFRESH_SECONDS is 2x

### ISSUE THREAD

**Issue by alevchuk** [jvstein/bitcoin-prometheus-exporter#3]
We're sleeping twice:
* https://github.com/jvstein/bitcoin-prometheus-exporter/blob/master/bitcoind-monitor.py#L222
* https://github.com/jvstein/bitcoin-prometheus-exporter/blob/master/bitcoind-monitor.py#L257

the first one can be removed.

Also, before the sleep we can add logging, e.g.:
```
        print(
            (
                "Refresh took {} seconds, sleeping for {} seconds"
            ).format(
                duration,
                REFRESH_SECONDS
            )
        )
```
Example output:
> Refresh took 0:00:01.965943 seconds, sleeping for 30.0 seconds
> Refresh took 0:00:02.020055 seconds, sleeping for 30.0 seconds
> Refresh took 0:00:02.032093 seconds, sleeping for 30.0 seconds
> Refresh took 0:00:02.042147 seconds, sleeping for 30.0 seconds

**Comment by jvstein** [comment]
Thanks for catching that!

I fixed the duplicate sleep call. I agree that some logging would be helpful, but definitely want to use the `logging` package and make the output level configurable. I don't see a need for such verbose logging most of the time.
